workflows:
  ios-workflow:
    name: iOS Debug Build (No Code Signing)
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - app_secrets
      vars:
        BUNDLE_ID: "com.yourname.eureka"
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
    
    scripts:
      - name: Create dummy .env if missing
        script: |
          touch .env
          
      - name: Disable Xcode Code Signing
        script: |
          sed -i '' 's/CODE_SIGNING_ALLOWED = YES/CODE_SIGNING_ALLOWED = NO/g' ios/Runner.xcodeproj/project.pbxproj
          sed -i '' 's/CODE_SIGNING_REQUIRED = YES/CODE_SIGNING_REQUIRED = NO/g' ios/Runner.xcodeproj/project.pbxproj
          sed -i '' '/DEVELOPMENT_TEAM/d' ios/Runner.xcodeproj/project.pbxproj
      
      - name: Get Flutter packages
        script: |
          flutter pub get
      
      - name: Flutter analyze
        script: |
          flutter analyze || true
      
      - name: Build iOS (Debug)
        script: |
          export CODE_SIGNING_ALLOWED=NO
          export CODE_SIGNING_REQUIRED=NO
          export CODE_SIGN_IDENTITY=""
          flutter build ios --debug --no-codesign --build-name=1.0.0 --build-number=1
      
      - name: Create IPA (manual signing)
        script: |
          cd build/ios/iphoneos
          mkdir Payload
          cp -r Runner.app Payload/
          zip -r app-debug.ipa Payload
          mv app-debug.ipa $CM_BUILD_DIR/
    
    artifacts:
      - app-debug.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true

  ios-release-workflow:
    name: iOS Release Build (Auto Signing)
    max_build_duration: 60
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: codemagic 
    environment:
      flutter: stable
      xcode: 15.0
      cocoapods: default
      groups:
        - app_secrets
      vars:
        BUNDLE_ID: "com.yourname.eureka"
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.yourname.eureka
    scripts:
      - name: Set up keychain
        script: |
          keychain initialize
      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files $BUNDLE_ID --type IOS_APP_STORE --create
      - name: Use certificate and profile
        script: |
          keychain add-certificates
          xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Build iOS Release
        script: |
          flutter build ipa --release --export-options-plist=$HOME/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
      email:
        recipients:
          - your-email@example.com
